image: python:3.7

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

pages:
  script:
    # Create the public directory
    - rm -rf public
    - mkdir public
    - mkdir -p public/docs
    - mkdir -p public/coverage
    - mkdir -p public/docs/apiwp
    # build jupyter book
    - pip install -U "jupyter-book"
    - jupyter-book build ./
    - mv ./_build/html/ public/
  artifacts:
    paths:
      - public
  only:
    - main

